### ISSUE TITLE
Improve UX for changing team name

### ISSUE THREAD

**Issue by leloykun** [admu-progvar/progvar-library#12]
**Context**
- Right now, it's a hassle to change the team name and other team identifiers in the notebook (i.e. teams needs to edit `notebook.tex` first before running the `makefile.sh`)

**Proposed Solution**
- Add a `team_name` command line argument to `/notebook/makefile.sh` that changes the team name in the notebook to the input. I.e. `makefile.sh --team_name TEAM_CHICKEN` would change the team name to `TEAM_CHICKEN`

**Comment by bullybutcher** [comment]
I implemented this but the flag I used was `-t`

Should I change it?

**Comment by leloykun** [comment]
@bullybutcher , close this ticket once you're done with your PR
